.PHONY : clean

cleanBuild :
	rm -rf .metals
	rm -rf project
	rm -rf .bloop
	rm -rf .vscode
	rm -rf target
	rm -rf verilog

clean :
	rm -rf .metals
	rm -rf project
	rm -rf .bloop
	rm -rf .vscode
	rm -rf target

verilog :
	sbt run
